name: Deploy #Name of the Workflow

on: #Name of the GitHub event that triggers the workflow
  pull_request: #On Push Event We need to take action
    branches: [main]
    types: [closed]

jobs: #Workflow run is made up of one or more jobs
  deploy_lambda:
    runs-on: ubuntu-latest #Through which Server OS we need to Work (type of machine to run the job on)
    steps:
      #Using versioned actions
      - uses: actions/checkout@v2 # --> Reference a specific version
      - uses: actions/setup-node@v2 # --> To Setup the Server With Node Env
        with:
          node-version: "18" #--> Specify the Version of the Node
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1 #--> Setup the Credential for the AWS cli
        with:
          # Created the Secrets Under the Repo only with These Variables
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: npm install
        env:
          CI: true
        run: npm ci
      - name: build project
        run: npm build
      - name: serverless deploy
        uses: serverless/github-action@v3.2
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
