name: Rodar Testes Unitários

on:
  pull_request:
    branches: [main, develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Instalar dependências
        run: npm ci
      - name: Rodar testes
        run: npm test
